# Nom du pipeline
name: Fruit et noms

on: workflow_dispatch
# Liste des jobs
jobs:
  # Nom du job
  run_script:
    # Type du runner (ici, un runner "shell")
    runs-on: ubuntu-latest
    # Steps à exécuter
    steps:
      # Récupération du script Bash
      - name: Checkout script
        uses: actions/checkout@v2
      # Exécution du script Bash
      - name: Run script
        run: |
          set -e
          fruits=("pomme" "banane" "orange" "kiwi")
          names=("Jean" "Sophie" "Emma")
          for fruit in "${fruits[@]}"
          do
            for name in "${names[@]}"
            do
              echo "${name} mange une ${fruit}, et il/elle adore ça !"
            done
          done