name: pull request

on:
  pull_request:
    types: [closed]

jobs:

  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        if: github.event.pull_request.merged == true
        run: echo "La PR a été mergée !"
