name: pull_request

on:
  pull_request:
    types: [closed]

jobs:

  pull:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        run: echo "La PR a été mergée !"
