name: pull_push

on: [push, pull_request]

env:
  PUSH: c'est un push !
  PR: C'est un PR !

jobs:
  
  push:
    runs-on: ubuntu latest 
    steps:
      - name: Push
        run: echo "$PUSH" 
  pull_request:
    runs-on: ubuntu-latest
    steps:  
      - name: Pull Request
        if: ${{ github.event_name == 'pull_request' }}     
        run: echo "$PR"