name: test request pull ou push ?

on: [push, pull_request]

env:
  PUSH: c'est un push !
  PR: C'est un PR !

jobs:
  
  push:
    runs-on: ubuntu latest 
    step:
      - name: Push
        run: echo "$PUSH" 
  pull_request:
    runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
      - name: Pull Request
        run: echo "PR" 
