name: Workflow-deux-jobs

on:
  workflow_dispatch:

jobs:
  job-manuel:
    runs-on: ubuntu-latest
    steps:
    - name: Envoyer un message manuellement
      run: echo "Le job manuel a été lancé !"

  job-automatique:
    runs-on: ubuntu-latest
    needs: job-manuel
    steps:
    - name: Envoyer un message automatiquement
      run: echo "Le job automatique a été lancé !"